Publish documentation for latest version of Android SDK
hellohaptik/docs_haptik pull request #367
Opened 2020-10-26 12:00 UTC by haptikrajasashtikar

- Publish documentation for Android SDK v7.0.0

2020-10-26 12:22 UTC, tejas-haptik requested changes
https://deploy-preview-367--goofy-saha-395bd1.netlify.app/android-sdk/#minimum-and-target-sdk-versions-of-the-haptik-sdk

We mention minSDK as 16 in document

2020-10-27 05:52 UTC, haptikrajasashtikar commented
> https://deploy-preview-367--goofy-saha-395bd1.netlify.app/android-sdk/#minimum-and-target-sdk-versions-of-the-haptik-sdk
> 
> We mention minSDK as 16 in document

Fair point will update

2020-10-27 05:57 UTC, imankur approved these changes

2020-10-27 07:52 UTC, tejas-haptik approved these changes
looks good

2020-10-27 07:54 UTC, merged