MyChats Revamp.md
hellohaptik/docs_haptik pull request #370
Opened 2020-11-05 14:47 UTC by medhaanand

2020-11-06 09:39 UTC, deepwired commented on docs/agent-chat/for-chat-agents.md
> +#### Agent Bar
We might need to rename this

2020-11-06 10:00 UTC, deepwired commented on docs/agent-chat/for-chat-agents.md
> +#### Agent Bar
Agent Details or Agent Status, or Agent name

2020-11-06 10:00 UTC, deepwired commented on docs/agent-chat/for-chat-agents.md
> +  * View Agent Status - Online or Offline
Offline -- might need to re-named

2020-11-06 10:00 UTC, deepwired commented on docs/agent-chat/for-chat-agents.md
> +  * View Agent Status - Online or Offline
might need more information here, we should create a new page for this.

2020-11-06 10:00 UTC, deepwired commented on docs/agent-chat/for-chat-agents.md
> +This section will give all numbers important for the agent.
Incoming, Existing and completed conversation ka information

2020-11-06 10:00 UTC, deepwired commented on docs/agent-chat/for-chat-agents.md
> +- **Agent queue**: Chats that have been manually assigned to the agent, or **Waiting for user** chats that has got a user reply
reassing chat --- instaed of assign chat

2020-11-06 10:00 UTC, deepwired commented on docs/agent-chat/for-chat-agents.md
> +- **Waiting for user**: Number of chats currently in waiting state of this agent.
waiting chats, instead of waiting for user chats.

2020-11-06 10:00 UTC, deepwired commented on docs/agent-chat/for-chat-agents.md
> +- **User name**: This is the name of the user. If the user has provided his name, that would show up or it will be **Guest User**.
team name is also present

2020-11-06 10:00 UTC, deepwired commented on docs/agent-chat/for-chat-agents.md
> +- **Last message time**: This will either be the first user message time (among consecutive user messages), or the latest agent reply time, whichever is earlier.
call this message time, instead of last message time.

2020-11-06 10:00 UTC, deepwired commented on docs/agent-chat/for-chat-agents.md
> +- **Number tab**: This is a tag showing number of messages that the agent has not yet read or responded to.
2 versions to this...

user unread or read messages... Tanvi was explaining something.

2020-11-06 10:00 UTC, deepwired commented on docs/agent-chat/for-chat-agents.md
> +- **Last message time**: This will either be the first user message time (among consecutive user messages), or the latest agent reply time, whichever is earlier.
separately mention unread and read ka timestamp scenarios

2020-11-10 05:34 UTC, deepwired commented on docs/agent-chat/for-chat-agents.md
> +#### Agent Bar
@medhaanand

2020-11-10 05:34 UTC, deepwired commented on docs/agent-chat/for-chat-agents.md
> +  * View Agent Status - Online or Offline
@medhaanand

2020-11-10 05:35 UTC, deepwired commented on docs/agent-chat/for-chat-agents.md
> +This section will give all numbers important for the agent.
we should change the text to portray the above description. @medhaanand

2020-11-10 05:35 UTC, deepwired commented on docs/agent-chat/for-chat-agents.md
> +- **Agent queue**: Chats that have been manually assigned to the agent, or **Waiting for user** chats that has got a user reply
small text change @medhaanand

2020-11-10 05:36 UTC, deepwired commented on docs/agent-chat/for-chat-agents.md
> +- **User name**: This is the name of the user. If the user has provided his name, that would show up or it will be **Guest User**.
description update @medhaanand

2020-11-10 05:36 UTC, deepwired commented on docs/agent-chat/for-chat-agents.md
> +- **Waiting for user**: Number of chats currently in waiting state of this agent.
renaming @medhaanand

2020-11-10 05:36 UTC, deepwired commented on docs/agent-chat/for-chat-agents.md
> +- **Last message time**: This will either be the first user message time (among consecutive user messages), or the latest agent reply time, whichever is earlier.
@medhaanand more info present on the design figma link

2020-11-10 20:43 UTC, medhaanand commented on docs/agent-chat/for-chat-agents.md
> +#### Agent Bar
```suggestion
#### Agent Details
```

2020-11-10 21:14 UTC, medhaanand commented on docs/agent-chat/for-chat-agents.md
> +  * View Agent Status - Online or Offline
Can you tell me what all an agent can do in online state and what all agent cant do in offline state @deepwired ?

2020-11-12 04:26 UTC, deepwired requested changes

2020-11-12 04:26 UTC, deepwired commented on docs/agent-chat/for-chat-agents.md
>  ## Logging in
lets remove this logging in thing, i don't think its required.

2020-11-12 04:26 UTC, deepwired commented on docs/agent-chat/for-chat-agents.md
> +In the online state ---- WAITING FOR DEEP's TEXT
```suggestion
Online State:
When an agent goes online,
-The agent will start receiving new chats as per his available slots.
-The agent could re-assign, mark as waiting, or complete any of the chats allocated to him

Offline State
When an agent goes Offline
- The agent will no longer receive any fresh chats
- The agent can no longer mark a chat as waiting
- All chats that were already marked as waiting by him/her will start assigning back to the agent so that they can close the chat, or re-assign the same
- The agent is expected to wrap up the chats that are already assigned to him

When an Agent Logsout
- All chats that are currently assigned to him/her will be auto completed.

```

2020-11-12 04:26 UTC, deepwired commented on docs/agent-chat/for-chat-agents.md
> +- **Waiting for user**: Number of chats sent in waiting state by this agent.
```suggestion
- **Waiting for user**: Number of chats currently in waiting state, as marked by this agent
```

2020-11-12 04:26 UTC, deepwired commented on docs/agent-chat/for-chat-agents.md
> +- **Agent queue**: Chats that have been manually reassigned to the agent and waiting chats where user has sent a response.
```suggestion
- **Agent queue**: Chats that have been manually reassigned to the agent either by a fellow team mate or a team lead, or chats that were marked as waiting, and the user has replied back.  
Note: Chats get added to the agent queue, only if the agent is at max concurrency.
```

2020-11-12 04:26 UTC, deepwired commented on docs/agent-chat/for-chat-agents.md
> +- **Team Queue**: Chats that are currently waiting to be taken up by the team.
```suggestion
- **Team Queue**: Chats that are currently waiting to be taken up by the agents of team, basis their slot availability. 
```

2020-11-12 04:26 UTC, deepwired commented on docs/agent-chat/for-chat-agents.md
> +- **Team name**: This is the name of the agent's team.
```suggestion
- **Team name**: This is the name of the team to which this chat is allocated.
```

2020-11-12 04:26 UTC, deepwired commented on docs/agent-chat/for-chat-agents.md
> +3. **Waiting longest**: This is a tag used for unread chats which have not had a reply for over 5 mins, or the longest waiting chat.
```suggestion
3. **Waiting longest**: This is a tag used for unread chats which have not had a reply for over 5 mins, or the longest waiting chat.

Note: For an agent, there will always be a maximum of one chat tagged as waiting longest.
```

2020-11-13 05:32 UTC, medhaanand commented on docs/agent-chat/for-chat-agents.md
>  ## Logging in
Done

2020-11-13 05:56 UTC, medhaanand commented on docs/agent-chat/for-chat-agents.md
> +In the online state ---- WAITING FOR DEEP's TEXT
Added

2020-11-13 08:23 UTC, closed without merging

2020-11-13 08:23 UTC, medhaanand commented
Creating a Fresh one