Balanced Distribution, Shared Agents support
hellohaptik/docs_haptik pull request #435
Opened 2021-03-15 03:59 UTC by deepwired

https://hello-haptik.atlassian.net/browse/AGCT-274
https://hello-haptik.atlassian.net/browse/AGCT-1086

2021-03-16 11:01 UTC, deepwired commented on docs/agent-chat/chat-assignment.md
> +We recommend keeping a lower agent concurrency for shared agents.
Note

2021-03-16 11:05 UTC, deepwired commented on docs/agent-chat/chat-assignment.md
> +We recommend keeping a lower agent concurrency for shared agents.
My Chats should show the real correct values for number of chats assigned/pinned as a test case

2021-03-16 11:05 UTC, deepwired commented on docs/agent-chat/chat-assignment.md
> +We recommend keeping a lower agent concurrency for shared agents.
he = his conc..

2021-03-16 11:06 UTC, deepwired commented on docs/agent-chat/chat-assignment.md
> +We recommend keeping a lower agent concurrency for shared agents.
If agent concurrency is C, and is a part of N teams following Balanced distribution, he concurrency will be C times N.    ---->>> he can get these many chats actually assigned.

2021-03-30 06:43 UTC, 1a8e requested changes

2021-03-30 06:43 UTC, 1a8e commented on docs/agent-chat/chat-assignment.md
> +6. Con(s): Does not account for faster agent response times but only the first response times. Faster high performing agents may not be best utilized.
- Shouldn't this be a continuation of point 5?
 - `Faster high performing agents may not be best utilized.`: seems a bit confusing, not sure what 'faster', 'high performing' mean in this context.

2021-03-30 06:43 UTC, 1a8e commented on docs/agent-chat/chat-assignment.md
> +> Note: We recommend keeping a lower agent concurrency for shared agents.
Should probably add a note stating you can't have agents shared across distribution mode types.

2021-03-30 06:43 UTC, 1a8e commented on docs/agent-chat/chat-assignment.md
> +i.e, If agent concurrency is C, and is a part of N teams that are following Balanced distribution algorithm, his/her concurrency will be C times N.
```suggestion
i.e, If agent's concurrency is C, and they are a part of N teams that are following Balanced distribution algorithm, their effective concurrency will be C times N.
```

2021-03-30 06:56 UTC, deepwired commented on docs/agent-chat/chat-assignment.md
> +> Note: We recommend keeping a lower agent concurrency for shared agents.
i'll put this point somewhere higher

2021-03-30 06:58 UTC, deepwired commented on docs/agent-chat/chat-assignment.md
> +6. Con(s): Does not account for faster agent response times but only the first response times. Faster high performing agents may not be best utilized.
If you have a single client and multiple businesses set up, all businesses must be the same algorithm

--- need to update this for clients with multiple teams and diff algos

2021-04-02 04:46 UTC, deepwired commented on docs/agent-chat/chat-assignment.md
> +> Note: We recommend keeping a lower agent concurrency for shared agents.
mentioned at the bottom, under Notes

2021-04-02 04:56 UTC, deepwired commented on docs/agent-chat/chat-assignment.md
> +6. Con(s): Does not account for faster agent response times but only the first response times. Faster high performing agents may not be best utilized.
changed the wordings by a bit

2021-04-02 09:51 UTC, medhaanand commented on docs/agent-chat/chat-assignment.md
> +6. Con(s): Unlike Speed Resolution, Quick high performing agents may not be best utilized.
```suggestion
6. Con(s): Unlike Speed Resolution, high performing agents may not be best utilised. 
```

2021-04-02 09:52 UTC, medhaanand commented on docs/agent-chat/chat-assignment.md
> +2. If there are multiple clients, one can select different algorithms for each.
This sentence does not need to be present as a separate point here, I think @deepwired

2021-04-02 12:50 UTC, deepwired commented on docs/agent-chat/chat-assignment.md
> +2. If there are multiple clients, one can select different algorithms for each.
1 - > single client multi business scenarios
2 - > multi client scenario
3 - > agent level stuff

we should keep 3 acc to me, open to re-wording.

2021-04-05 10:28 UTC, medhaanand commented on docs/agent-chat/chat-assignment.md
> +2. If there are multiple clients, one can select different algorithms for each.
Alright, rewording it slightly then.

2021-04-05 10:29 UTC, medhaanand commented on docs/agent-chat/chat-assignment.md
> +1. If you have a single client and multiple businesses set up, all businesses must use the same algorithm.
```suggestion
1. If there is a single client and multiple businesses set up, all businesses must use the same algorithm.
```

2021-04-05 10:30 UTC, medhaanand commented on docs/agent-chat/chat-assignment.md
> +2. If there are multiple clients, one can select different algorithms for each.
```suggestion
2. If there are multiple clients, no compulsion of using same algorithm. One can select different algorithms for each.
```

2021-04-05 11:42 UTC, medhaanand approved these changes

2021-04-05 13:47 UTC, 1a8e approved these changes

2021-04-05 13:47 UTC, merged