Update SLA and Help
hellohaptik/docs_haptik pull request #461
Opened 2021-04-22 13:59 UTC by rasika-purohit

[skip ci]

2021-05-10 06:23 UTC, srajdev requested changes

2021-05-10 06:23 UTC, srajdev commented on docs/other/sla.md
> +If you have questions or run into technical issues while using Haptik, you can access our guides and tutorials for self-guided instructions and troubleshooting tips. We also provide additional suppor
The first line is pushing towards more guided tutorials and self guided instructions. So the minute I start reading it it sounds like all the support I am going to get is going to be very mechanical in nature and will be hard for me to talk to a person. While based on what we had discussed and we need to make it simpler for people to reach out to us and make it sound like that as well.

2021-05-10 06:23 UTC, srajdev commented on docs/other/sla.md
> +To get help, you must be logged in and go through our [**HELP section**](https://docs.haptik.ai/other/supportbot) or send us an email at **support@haptik.ai**. When you log in to your account, we’re
1. We should mention email before the help section.
2. Why id HELP in capital?
3. what about being able to call my CS/PM person directly?

2021-05-10 06:23 UTC, srajdev commented on docs/other/sla.md
> +### How to contact technical support?
This section should come before the access the guides and tutorials. Having that first means we are pushing that harder and just like the first point will make it feel like it is hard for the customer to reach out to people and get help.

2021-05-10 06:23 UTC, srajdev commented on docs/other/sla.md
> +### Access the guides and tutorials
We should make the copy better, it sounds very transactional right now. 
Example like:
"If you don't like calling or email people and want to try and find answers yourself, we have a very comprehensive documentation and tutorials. You can access them here. You can also use the search feature on top to find the exact section you are looking for"

2021-05-10 06:23 UTC, srajdev commented on docs/other/sla.md
> +To contact our support team, follow these steps -
the first comment is repetitive (Find the HELP section_ is above as well

2021-05-10 06:23 UTC, srajdev commented on docs/other/sla.md
> +## Severity & Response Time
Throughout the documentation if i am being directed via bot or email all i keep thinking is how long will it take for me to get my answer. The SLA needs to come above I feel.

2021-05-10 06:23 UTC, srajdev commented on docs/other/sla.md
> +## Uptime
We should explain how SLA and uptime are different. While i know in the industry this might be a norm i've realised a lot of our customers have these questions. They will be like isint a S0 and uptime the same thing? How do i differentiate etc

2021-05-11 09:25 UTC, medhaanand commented on docs/other/sla.md
> +If you have questions or run into technical issues while using Haptik, you can access our guides and tutorials for self-guided instructions and troubleshooting tips. We also provide additional suppor
What is Haptik Support?

Haptik Guidance and the Customer Success Team is always be there to help you during your journey with Haptik. Along with that, we also have a TST to help you with any questions on the platform or the deployed solution.

2021-05-17 07:38 UTC, srajdev requested changes

2021-05-17 07:38 UTC, srajdev commented on docs/other/support.md
> +Haptik Support provides you with everything which will help you achieve your outcomes and find success. It is mix of tools and technology, people, and resources designed to proactively help you find
Too long a paragraph in the beginning. My suggestion would be to keep it something like: 

Haptik Support provides you with everything to help you achieve your outcomes and find success. It is mix of tools, technology, people, and resources designed to proactively help you find quick solutions, optimize performance, lower costs, and innovate faster. We aim to provide best in class support by answering best practices questions, guidance on configuration, all the way to break-fix and problem resolution.

2021-05-17 07:38 UTC, srajdev commented on docs/other/support.md
> +### Where can you access **Help section**?
Put the SLA section before this. That more important than this section

2021-05-17 07:38 UTC, srajdev commented on docs/other/support.md
> +We’re here to help to -
Isin't this point already said before in the first paragraph?

2021-05-17 07:38 UTC, srajdev commented on docs/other/support.md
> +We aim to provide best in class support. Haptik Guidance and the Customer Success Team is always there to help you during your journey with Haptik. Along with that, we also have a dedicated Support t
Not sure what point we want to drive with this paragraph.

2021-05-17 15:26 UTC, medhaanand commented on docs/other/support.md
> +Haptik Support provides you with everything which will help you achieve your outcomes and find success. It is mix of tools and technology, people, and resources designed to proactively help you find
Done

2021-05-17 15:27 UTC, medhaanand commented on docs/other/support.md
> +We’re here to help to -
Yes kinda repetitive.

2021-05-17 15:28 UTC, medhaanand commented on docs/other/support.md
> +We aim to provide best in class support. Haptik Guidance and the Customer Success Team is always there to help you during your journey with Haptik. Along with that, we also have a dedicated Support t
Just to tell them that Guidance and CS team would also help them and Support team is additional to it. Very similar to the point, we have mentioned below that you can reach out to Haptik SPOC too. If you think its not necessary, will remove it.

2021-05-17 15:30 UTC, medhaanand commented on docs/other/support.md
> +### Where can you access **Help section**?
Done

2021-05-27 10:00 UTC, medhaanand approved these changes

2021-05-27 11:50 UTC, closed without merging